-- HOMEWORK 2
-- EDILSON ALBERTO, BESNIK SHUAIPAJ, WILL MORRISSEY, HRIDETA RIMU
-- EXERCISE 1
SELECT * FROM hw2.coach;
SELECT * FROM hw2.person;
SELECT * FROM hw2.player;
SELECT * FROM hw2.team;
-- EXERCISE 2
SELECT * 
FROM hw2.team
ORDER BY `TmID` ASC;

-- EXERCISE 3
SELECT * 
FROM hw2.team
WHERE `Name` LIKE 'MIL%W%K%';
